### ISSUE TITLE
compile failed with cordova ios 4.0.0

### ISSUE THREAD

**Issue by raymatos** [driftyco/ionic-plugin-keyboard#154]
```
** BUILD FAILED **


The following build commands failed:
	CompileC build/Styrka\ Ballistics.build/Debug-iphonesimulator/Styrka\ Ballistics.build/Objects-normal/i386/IonicKeyboard.o Styrka\ Ballistics/Plugins/com.ionic.keyboard/IonicKeyboard.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
ERROR building one of the platforms: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/raymatos/Documents/Ballistic-Hybird-App/platforms/ios/cordova/build-debug.xcconfig,-project,Styrka Ballistics.xcodeproj,ARCHS=i386,-target,Styrka Ballistics,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/raymatos/Documents/Ballistic-Hybird-App/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/raymatos/Documents/Ballistic-Hybird-App/platforms/ios/build/sharedpch
You may not have the required environment or OS to build this project
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/raymatos/Documents/Ballistic-Hybird-App/platforms/ios/cordova/build-debug.xcconfig,-project,Styrka Ballistics.xcodeproj,ARCHS=i386,-target,Styrka Ballistics,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/raymatos/Documents/Ballistic-Hybird-App/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/raymatos/Documents/Ballistic-Hybird-App/platforms/ios/build/sharedpch
```

**Comment by drastick** [comment]
+1

**Comment by oallouch** [comment]
xxxxxx/Plugins/com.ionic.keyboard/IonicKeyboard.m:75:22: error: 
      property 'hackishlyHidesInputAccessoryView' not found on object of type 'UIView *'
        self.webView.hackishlyHidesInputAccessoryView = YES;


+1000

**Comment by sbezkostnyi** [comment]
It's related to API changes in cordova-ios 4.0.0. See details: https://github.com/apache/cordova-ios/blob/master/guides/API%20changes%20in%204.0.md

**Comment by oallouch** [comment]
I can't code in Objective C, but looks like a simple cast to me.

**Comment by macdonst** [comment]
Update to version 1.0.8 as it is fixed.

**Comment by oallouch** [comment]
Thx !
I guess I missed the plugin name change :)

**Comment by tlancina** [comment]
Going to close as a duplicate of #102.  This should be fixed in 1.0.8, please comment on that issue if you're still having problems!

**Comment by barocsi** [comment]
Cordova 4.0 error
The following build commands failed:
	CompileC build/xxx.build/Debug-iphoneos/xxx.build/Objects-normal/armv7/MainViewController.o xxx/Classes/MainViewController.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by klh** [comment]
this is still an issue
and you rename the plugin as well - so you should refer user to install https://github.com/driftyco/ionic-plugin-keyboard
